/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cubism cdi3.json File Format
 */
export interface Cdi3 {
  /**
   * Json file format version.
   */
  Version: number;
  /**
   * All Parameters.
   */
  Parameters: Parameter[];
  /**
   * All ParameterGroups.
   */
  ParameterGroups?: ParameterGroup[];
  /**
   * All Parts.
   */
  Parts: Part[];
}
/**
 * Parameter data.
 */
export interface Parameter {
  /**
   * Identifier for the parameter.
   */
  Id: string;
  /**
   * Identifier for the parent group of the parameter.
   */
  GroupId: string;
  /**
   * Name of the parameter.
   */
  Name: string;
}
/**
 * Parameter group data.
 */
export interface ParameterGroup {
  /**
   * Identifier for the parameter group.
   */
  Id: string;
  /**
   * Identifier for the parent group of the parameter group.
   */
  GroupId: string;
  /**
   * Name of the parameter group.
   */
  Name: string;
}
/**
 * Part data.
 */
export interface Part {
  /**
   * Identifier for the part.
   */
  Id: string;
  /**
   * Name of the part.
   */
  Name: string;
}
