/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cubism exp3.json File Format
 */
export interface Exp3 {
  /**
   * Json file format type.
   */
  Type: 'Live2D Expression';
  /**
   * [Optional] Time of the Fade-In for easing in seconds.
   */
  FadeIn?: number;
  /**
   * [Optional] Time of the Fade-Out for easing in seconds.
   */
  FadeOut?: number;
  /**
   * Targeted parameter list.
   */
  Parameters: Parameter[];
}
/**
 * Parameter data.
 */
export interface Parameter {
  Id: string;
  Value: number;
  Blend: 'Add' | 'Multiply' | 'Overwrite';
}
