/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cubism pose3.json File Format
 */
export interface Pose3 {
  /**
   * Json file format type.
   */
  Type: 'Live2D Pose';
  /**
   * Time of the Fade-In for easing in seconds.
   */
  FadeInTime?: number;
  /**
   * List of the switching control groups.
   */
  Groups: Node[][];
}
/**
 * Switching control node.
 */
export interface Node {
  /**
   * Main switching Part ID.
   */
  Id: string;
  /**
   * List of the linked switching Part IDs.
   */
  Link: string[];
}
