/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Cubism userdata3.json File Format
 */
export interface Userdata3 {
  /**
   * Json file format version.
   */
  Version: number;
  /**
   * Additional data describing the user data.
   */
  Meta: {
    /**
     * The total number of UserData.
     */
    UserDataCount: number;
    /**
     * The total size of UserData in bytes.
     */
    TotalUserDataSize: number;
  };
  /**
   * User data.
   */
  UserData: UserData[];
}
/**
 * User data.
 */
export interface UserData {
  /**
   * Target type.
   */
  Target: string;
  /**
   * Identifier for mapping to target.
   */
  Id: string;
  /**
   * Content of user data.
   */
  Value: string;
}
